#location of star
star: /cluster/project8/vyp/vincent/Software/STAR-STAR_2.4.2a/bin/Linux_x86_64_static/STAR

cutadapt: /share/apps/python-2.7.8/bin/cutadapt
fastqc: /share/apps/genomics/fastqc-0.11.2/