__default__:
    h_vmem: 4G
    h_rt:   1:0:0
    pe: smp 1
    R:  y

fastqc:
    h_vmem:    4G
    tmem:   4G
    h_rt: 72:00:00
    
multiqc:
    h_vmem:    4G
    tmem:   4G
    h_rt: 72:00:00

fastp_trimming:
    h_vmem:    4G
    tmem:   4G
    h_rt: 72:00:00

run_star_pe:
    h_vmem:   2.6G
    tmem:   2.6G
    pe: smp 12
    h_rt: 72:00:00

run_star_se:
    h_vmem:   2.6G
    tmem:   2.6G
    pe: smp 12
    h_rt: 72:00:00