######UPDATE THIS SECTION WITH RUN SPECIFIC INFORMATION#########
######UPDATE THIS SECTION WITH RUN SPECIFIC INFORMATION#########
######UPDATE THIS SECTION WITH RUN SPECIFIC INFORMATION#########
#path to a csv with the follwing format: 
#sample_name,unit, fast1,fast2
#if the data is single end leave the fast2 column blank
sampleCSVpath: /SAN/vyplab/IoN_RNAseq/Bilal_Muscle_biopsies/analysis/wide_fastq.csv
end_type: pe
fastqc_output_folder: /SAN/vyplab/IoN_RNAseq/Bilal_Muscle_biopsies/analysis/fastqc/
fastp_trimmed_output_folder: /SAN/vyplab/IoN_RNAseq/Bilal_Muscle_biopsies/analysis/fastp_trimmed/
star_output_folder: /SAN/vyplab/TDP43_RNA/4SU_mouse/STAR_aligned/

######UPDATE THIS SECTION WITH RUN SPECIFIC INFORMATION#########
######UPDATE THIS SECTION WITH RUN SPECIFIC INFORMATION#########
# sampleCSVpath: /SAN/vyplab/TDP43_RNA/4SU_mouse/fastq_locations_4su.csv
# end_type: se
# fastqc_output_folder: /SAN/vyplab/TDP43_RNA/4SU_mouse/fastqc/
# fastp_trimmed_output_folder: /SAN/vyplab/TDP43_RNA/4SU_mouse/fastp_trimmed/

# star_output_folder: /SAN/vyplab/TDP43_RNA/4SU_mouse/STAR_aligned/

#mouse or human
species: "mouse"
#species: "human"

######IF YOU DON'T KNOW WHAT YOU'RE DOING DON'T FIDDLE WITH THESE NEXT LINES#########
######IF YOU DON'T KNOW WHAT YOU'RE DOING DON'T FIDDLE WITH THESE NEXT LINES#########
######IF YOU DON'T KNOW WHAT YOU'RE DOING DON'T FIDDLE WITH THESE NEXT LINES#########

#########################
##FASTQC PARAMETERS######
#########################

#path to the fastqc executable
fastqc_path: /share/apps/genomics/fastqc-0.11.2/fastqc



#########################
##FASTP PARAMETERS - TRIMMING HERE######
#########################
fastp_path: /home/annbrown/fastp

#quality trimming is debated, and harsh cutoff can effect expression, using a soft quality trim of 10 based on this paper
#https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-016-0956-2
#use this flag if there are UMI's present, if there are, there should be a file with fastq & umi fastq present, otherwise 
#additional parameters you might want to add on
fastp_parameters:
  qualified_quality_phred: 10
  #use this flag if there are UMI's present, if there are, there should be a file with fastq & umi fastq present, otherwise 
  #leave this flag as an empty string: ""
  #umi: ""
  #umi_loc: /SAN/vyplab/IoN_RNAseq/Bilal_Muscle_biopsies/analysis/fastqc/


#########################
##STAR PARAMETERS - ALIGNMENT HERE######
#########################
#location of star exe
star_path: /cluster/project8/vyp/vincent/Software/STAR-STAR_2.4.2a/bin/Linux_x86_64_static/STAR

extra_star_parameters:
  outSAMattributes: MD NH
  alignEndsType: EndToEnd
  quantMode: GeneCounts
  outSAMtype: BAM SortedByCoordinate 
  twopassMode: Basic
  twopass1readsN: -1

star_genome_mouse:
star_genome_human:


cutadapt: /share/apps/python-2.7.8/bin/cutadapt

#path to the multiqc file ######HOPEFULLY THIS WILL BE REPLACED BY A SHARE LOCATION, CURRENTLY JUST INSTALLED ON MY HOMEDRIVE
multiqc_path: /home/annbrown/.local/bin/multiqc
###for any additional multiqc runtime commands, if you want them it would be something like --cl_config "qualimap_config: { general_stats_coverage: [20,40,200] }", otherwise leave the parameter blank
multiqc_configparams: ""